### ISSUE TITLE
pull-backup parameters reversed

### ISSUE THREAD

**Issue by x4x** [AlbertWeichselbraun/borg-backup-scripts#1]
hi,
im trying out your pull-backup.sh but i found some inconsistencies.

1.  curently parameter 1 is the hostname and parameter 2 is the backup repo. this is reverse to the documentation/help.
2.  on debian i also needet to install 'killall' `apt install psmisc` and `apt install uuid-runtime`.

**Comment by AlbertWeichselbraun** [comment]
thank you for spotting these issues.  I have corrected them in the master branch.
please let me know, if you run across any other problems.

cheers, albert :)
